### PR TITLE
Set BuildingInsideVisualStudio to load WPF projects

### LINKED ISSUE #1337: WPF projects don't compile
Steps to reproduce:

```sh
mkdir WpfFormat
cd WpfFormat
dotnet new wpf
dotnet format --verify-no-changes
```

The resulting error is:

`MainWindow.xaml.cs(25,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [WpfFormat.csproj]`

### PR DESCRIPTION
**Pull request by JoeRobich**
Resolves #1337

### CODE REVIEW

**Comment by JoeRobich** [comment]
Taking this PR would cause the same regressions in blazor and blazorwasm scenarios as described in https://github.com/dotnet/roslyn/pull/69225#discussion_r1278207379. I would prefer to see https://github.com/dotnet/roslyn/pull/69225 merge in as it does not regress project loading.
